### ISSUE TITLE
Upload Fail

### ISSUE THREAD

**Issue by smayleee** [google/play-instant-unity-plugin#34] opened 2018-08-30 15:22 UTC
We got a problem when we try to upload .zip file to Google Play developer Console
this is message:

> Your Instant App APKs do not declare a valid 'android:targetSandboxVersion' attribute in their AndroidManifest. Using the 'com.android.feature' Gradle plugin to build your Instant App would add this attribute automatically.

Did we miss something?

**Comment by thanwah** [comment] 2018-08-30 16:02
Hi, thank you for posting this issue.

One feature of the plugin is to automatically add the "android:targetSandboxVersion" attribute to the AndroidManifest. I'm sorry to hear that it didn't work in your case.

To help me narrow down the cause, do you mind sharing:
- the version of Unity that you're using
- whether you're using the Gradle or Internal Build System
- whether you have any existing AndroidManifest files, e.g. under Assets/Plugins/Android/

**Comment by smayleee** [comment] 2018-08-30 16:07
Hi, thanks for fast reply!
We saw that feature to automatically add "android:targetSandboxVersion" thats why i post question here.

- Unity version is: 2017.3.1f1
- Build System is Gradle
- No other AndroidManifest.xml file in project at all. (when i try to add my AndroidManifest application wont start)

**Comment by thanwah** [comment] 2018-08-30 18:53
Thanks for the additional context.

If you go into the Play Instant Build Settings window and switch from "Installed" to "Instant" mode or vice versa and then Save, do you see any messages in the Console log? Or does it say "Successfully updated Assets/Plugins/Android/AndroidManifest.xml"?

If you navigate in Unity to the Assets/Plugins/Android folder and right-click to get the context menu to "Refresh", do you see the AndroidManifest.xml file there?

There may be some workarounds that I can suggest, but first I'd like to understand why it's not working to see if we can fix the underlying issue.

**Comment by smayleee** [comment] 2018-08-30 19:02
Hi, when i try to save AssetBundleManifest path, editor say "Successfully updated Assets/Plugins/Android/AndroidManifest.xml"

but this is the manifest i got 

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:targetSandboxVersion="2">
  <application>
    <activity android:name="com.unity3d.player.UnityPlayerActivity">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>
  </application>
</manifest>
```
(no android:targetSandboxVersion by auto generated script)

I made it WORK like this:

i found hidden manifest in my Unity project Temp folder
copy that manifest in Plugins folder
Add manually "android:targetSandboxVersion"
and it works

**Comment by thanwah** [comment] 2018-08-30 21:07
I'm glad that you have something working now.

I may be misunderstanding, but in the manifest snippet that you shared I see `android:targetSandboxVersion="2"` on the 2nd line. That looks correct to me.

Note that the "hidden manifest in my Unity project Temp folder" may be overwritten or deleted occasionally since it's a temporary build artifact. It may become tedious to update it each time.

**Comment by smayleee** [comment] 2018-08-31 18:55
Hi, 
Temp manifest did not have `android:targetSandboxVersion="2"` we have to add it each time.
If we add Plugins/Android/AndroidManifest.xml with Unity editor feature(PlayInstant/BuildSettings/AssetBundleManifest) game won't launch 

Other version of Unity takes more than **10mb** (10,3~4) so we have to use version 2017.3.1f1. 
If you know better version of Unity we will be thankful to know!

**Comment by thanwah** [comment] 2020-03-25 23:45
Closing this issue. If there is still a problem, please resubmit here: https://github.com/google/play-unity-plugins/issues

**Closed by thanwah** 2020-03-25 23:45 UTC
